### ISSUE TITLE
Weird underline position/thickness

### ISSUE THREAD

**Issue by userNeptune** [canonical/UbuntuMono-fonts#16]
Same issue as the Ubuntu family, related [canonical/Ubuntu-fonts#24](https://github.com/canonical/Ubuntu-fonts/issues/24) and [canonical/Ubuntu-fonts#61](https://github.com/canonical/Ubuntu-fonts/issues/61)

**Comment by djrrb** [comment]
Current Ubuntu Mono values (position, thickness):

- UbuntuMono-Bold.ttf -138 79
- UbuntuMono-BoldItalic.ttf -138 79
- UbuntuMono-ExtraLight.ttf -138 79
- UbuntuMono-Italic.ttf -138 79
- UbuntuMono-Light.ttf -138 79
- UbuntuMono-Medium.ttf -138 79
- UbuntuMono-MediumItalic.ttf -138 79
- UbuntuMono-Regular.ttf -138 79
- UbuntuMono-SemiBold.ttf -138 79
- UbuntuMono-SemiBoldItalic.ttf -138 79
- UbuntuMono-Thin.ttf -138 79


Current Ubuntu values (position, thickness):

- Ubuntu-Bold.ttf -138 79
- Ubuntu-BoldItalic.ttf -138 79
- Ubuntu-ExtraBold.ttf -138 79
- Ubuntu-ExtraBoldItalic.ttf -138 79
- Ubuntu-ExtraLight.ttf -138 79
- Ubuntu-ExtraLightItalic.ttf -138 79
- Ubuntu-Italic.ttf -138 79
- Ubuntu-Light.ttf -138 79
- Ubuntu-LightItalic.ttf -138 79
- Ubuntu-Medium.ttf -138 79
- Ubuntu-MediumItalic.ttf -138 79
- Ubuntu-Regular.ttf -138 79
- Ubuntu-SemiBold.ttf -138 79
- Ubuntu-SemiBoldItalic.ttf -138 79
- Ubuntu-Thin.ttf -138 79
- Ubuntu-ThinItalic.ttf -138 79
- UbuntuCondensed-Bold.ttf -138 79
- UbuntuCondensed-BoldItalic.ttf -138 79
- UbuntuCondensed-ExtraBold.ttf -138 79
- UbuntuCondensed-ExtraBoldItalic.ttf -138 79
- UbuntuCondensed-ExtraLight.ttf -138 79
- UbuntuCondensed-ExtraLightItalic.ttf -138 79
- UbuntuCondensed-Italic.ttf -138 79
- UbuntuCondensed-Light.ttf -138 79
- UbuntuCondensed-LightItalic.ttf -138 79
- UbuntuCondensed-Medium.ttf -138 79
- UbuntuCondensed-MediumItalic.ttf -138 79
- UbuntuCondensed-Regular.ttf -138 79
- UbuntuCondensed-SemiBold.ttf -138 79
- UbuntuCondensed-SemiBoldItalic.ttf -138 79
- UbuntuCondensed-Thin.ttf -138 79
- UbuntuCondensed-ThinItalic.ttf -138 79


As you found in the old issues I had previously set the thicknesses by weight. Now they are now set consistently to comply with this fontbakery check: https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/post.html

Unfortunately, feel like my hands are tied a little bit this one unless the decision is made to ignore that check? Comments welcome.
