### ISSUE TITLE
fi/fl ligatures mess with spacing in linux terminal

### ISSUE THREAD

**Issue by jastko** [canonical/UbuntuMono-fonts#7]
Font version: `Ubuntu Mono 0.869`
OS: `Linux`
Terminal: `KDE/Konsole`

![konsole_tty](https://github.com/canonical/UbuntuMono-fonts/assets/134521733/afa55a76-e4c2-4abc-b876-386f400be428)

**Comment by guidoferreyra** [comment]
Fixed on [a3567ab](https://github.com/canonical/UbuntuMono-fonts/commit/a3567abf31c4b69919e1f3e8ed397aa5baf3f01c)
