### ISSUE TITLE
Variable font is missing SemiBold weight

### ISSUE THREAD

**Issue by jastko** [canonical/UbuntuMono-fonts#9]
OS: `Linux`
Font version: `1.000 (main branch)`

Cannot select `SemiBold` weight. Picture below.
![nosemibold_select](https://github.com/canonical/UbuntuMono-fonts/assets/134521733/c24f03bb-470f-4411-9789-5e8f56670344)

Probable cause is wrong name for `SemiBold` weight. `fc-list -v "Ubuntu Mono" | grep -E "fullname:|weight"` reports two instances of `Ubuntu Mono Light`, one with weight `180(semibold)`, and on with weight `50(Light)`. Picture below.
![nosemibold_mark](https://github.com/canonical/UbuntuMono-fonts/assets/134521733/0bfa8770-f6af-437e-aa2b-b25d5fb54fa7)

**Comment by djrrb** [comment]
Thank you so much for catching this error! I believe it was due to a typo on my part. 

Can you confirm that the SemiBold weight appears as expected in the latest commit ebfc0bc74671d7b5f87dd8a068731fe8ead79dea?

Much appreciated!

**Comment by jastko** [comment]
Now it works as expected.

**Comment by jastko** [comment]
Now it works as expected.
